### ISSUE TITLE
Intended purpose of notmuch backend?

### ISSUE THREAD

**Issue by eterps** [pimalaya/neverest#10]
What is the intended purpose of the notmuch backend?

Is the idea that you can sync from imap to a notmuch backend directly? (so that notmuch does not need to be installed/configured on your system?)

An email client like [aerc](https://aerc-mail.org) can use a notmuch backend directly, it seems you would not need a Maildir at all in that case.
But neverest does not seem to create a notmuch DB, and notmuch itself still depends on a Maildir being present.

Sorry if this is rather obvious, but I have trouble seeing the big picture.

**Comment by soywod** [comment]
Initially the notmuch backend comes from [Himalaya](https://github.com/pimalaya/himalaya), and like aerc it makes sense. For Neverest it's a bit less obvious. The only advantage of using notmuch over maildir is that you do not need to re-index messages. If you manipulate directly the maildir, notmuch is not aware of changes and the db needs to be update manually. If you use the notmuch backend, then it manipulates the maildir and takes care of updating the database.

**Comment by eterps** [comment]
Thanks, I think I understand now. You will usually sync to Maildir+notmuch, and in that case it removes the need to do `notmuch new`.

**Comment by soywod** [comment]
Yes. If Neverest was alone, it would not make sense to specifically develop the notmuch backend. But since notmuch support is already there in the Pimalaya core `email-lib`, it does not cost that much to propose it.
